### PR TITLE
Some RTMP changes

### PR DESCRIPTION
**Pull request by TechWhizZ199**

### CODE REVIEW

**Comment by swiftSwathSee** [comment]
Isn't this redundant? There's already a "_was banned._" message when you get banned, this just adds an additional "_You have been banned from the room._" It also doesn't solve #36, which calls for a ban notification when you first connect to a room that you've previously been banned from (i.e. the same "You have been logged out" thing that the Flash client does upon connection.)

```
55:11:32 pything: uh ban me
55:11:33 pything was banned.
55:11:33 You have been banned from the room!.
```

**Comment by TechWhizZ199** [comment]
There was a "kick" AMF message already in place. That is why it appears redundant, I am sure you can just put underneath the "kick" message that if the nickname that was kicked was the clients i.e. yours then just ignore or continue with the listen() function else print it out. I have included banned since it gives more of a function to the library. On the contrary to your second point, #36 the "banned" message should print out since that is the message which states that you have already been banned from a room. I'll make the changes required.

**Comment by TechWhizZ199** [comment]
I also have sent you an invite to a project we (as in several other coders) are working on. I am not sure if you would like to join or not but feel free to. https://github.com/oddballz

**Comment by swiftSwathSee** [comment]
It isn't printing the ban message upon connection. I tested it straight from your fork.

**Comment by TechWhizZ199** [comment]
It should do. I will look into this when I have some free time.

**Comment by swiftSwathSee** [comment]
Thanks. Merging this for now since I'll be pushing my own commits soon and don't want too many possible conflicts later on.

**Comment by TechWhizZ199** [comment]
No great work! Keep it up, though are you still willing to join me and a couple of other coders?

**Pull request merged**
